package com.bawnorton.vrt.addons.items;

import com.bawnorton.vrt.addons.blocks.VRTBlockInit;
import com.bawnorton.vrt.addons.blocks.VRTTaintBlock;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Hashtable;
import java.util.List;

public class VRTItemInit {

    public static final List<Item> ITEMS = new ArrayList<>();

    //
    // Item Blocks
    //
    //
    // BLOCKS
    //
    public static final Item TAINTED_ANDESITE = new ItemBlock(VRTBlockInit.TAINTED_ANDESITE);
    public static final Item MOSTLY_TAINTED_ANDESITE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ANDESITE);
    public static final Item PARTIALLY_TAINTED_ANDESITE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ANDESITE);
    public static final Item SLIGHTLY_TAINTED_ANDESITE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ANDESITE);
    public static final Item TAINTED_CLAY = new ItemBlock(VRTBlockInit.TAINTED_CLAY);
    public static final Item MOSTLY_TAINTED_CLAY = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_CLAY);
    public static final Item PARTIALLY_TAINTED_CLAY = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_CLAY);
    public static final Item SLIGHTLY_TAINTED_CLAY = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_CLAY);
    public static final Item TAINTED_COBBLESTONE = new ItemBlock(VRTBlockInit.TAINTED_COBBLESTONE);
    public static final Item MOSTLY_TAINTED_COBBLESTONE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_COBBLESTONE);
    public static final Item PARTIALLY_TAINTED_COBBLESTONE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_COBBLESTONE);
    public static final Item SLIGHTLY_TAINTED_COBBLESTONE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_COBBLESTONE);
    public static final Item TAINTED_DIORITE = new ItemBlock(VRTBlockInit.TAINTED_DIORITE);
    public static final Item MOSTLY_TAINTED_DIORITE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_DIORITE);
    public static final Item PARTIALLY_TAINTED_DIORITE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_DIORITE);
    public static final Item SLIGHTLY_TAINTED_DIORITE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_DIORITE);
    public static final Item TAINTED_DIRT = new ItemBlock(VRTBlockInit.TAINTED_DIRT);
    public static final Item MOSTLY_TAINTED_DIRT = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_DIRT);
    public static final Item PARTIALLY_TAINTED_DIRT = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_DIRT);
    public static final Item SLIGHTLY_TAINTED_DIRT = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_DIRT);
    public static final Item TAINTED_GRANITE = new ItemBlock(VRTBlockInit.TAINTED_GRANITE);
    public static final Item MOSTLY_TAINTED_GRANITE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_GRANITE);
    public static final Item PARTIALLY_TAINTED_GRANITE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_GRANITE);
    public static final Item SLIGHTLY_TAINTED_GRANITE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_GRANITE);
    public static final Item TAINTED_GRAVEL = new ItemBlock(VRTBlockInit.TAINTED_GRAVEL);
    public static final Item MOSTLY_TAINTED_GRAVEL = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_GRAVEL);
    public static final Item PARTIALLY_TAINTED_GRAVEL = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_GRAVEL);
    public static final Item SLIGHTLY_TAINTED_GRAVEL = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_GRAVEL);
    public static final Item TAINTED_SAND = new ItemBlock(VRTBlockInit.TAINTED_SAND);
    public static final Item MOSTLY_TAINTED_SAND = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_SAND);
    public static final Item PARTIALLY_TAINTED_SAND = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_SAND);
    public static final Item SLIGHTLY_TAINTED_SAND = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_SAND);
    public static final Item TAINTED_SANDSTONE = new ItemBlock(VRTBlockInit.TAINTED_SANDSTONE);
    public static final Item MOSTLY_TAINTED_SANDSTONE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_SANDSTONE);
    public static final Item PARTIALLY_TAINTED_SANDSTONE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_SANDSTONE);
    public static final Item SLIGHTLY_TAINTED_SANDSTONE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_SANDSTONE);
    public static final Item TAINTED_STONE = new ItemBlock(VRTBlockInit.TAINTED_STONE);
    public static final Item MOSTLY_TAINTED_STONE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_STONE);
    public static final Item PARTIALLY_TAINTED_STONE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_STONE);
    public static final Item SLIGHTLY_TAINTED_STONE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_STONE);
    public static final Item TAINTED_STONE_BRICKS = new ItemBlock(VRTBlockInit.TAINTED_STONE_BRICKS);
    public static final Item MOSTLY_TAINTED_STONE_BRICKS = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_STONE_BRICKS);
    public static final Item PARTIALLY_TAINTED_STONE_BRICKS = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_STONE_BRICKS);
    public static final Item SLIGHTLY_TAINTED_STONE_BRICKS = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_STONE_BRICKS);
    public static final Item TAINTED_ORE_BAUXITE = new ItemBlock(VRTBlockInit.TAINTED_ORE_BAUXITE);
    public static final Item MOSTLY_TAINTED_ORE_BAUXITE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_BAUXITE);
    public static final Item PARTIALLY_TAINTED_ORE_BAUXITE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_BAUXITE);
    public static final Item SLIGHTLY_TAINTED_ORE_BAUXITE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_BAUXITE);
    public static final Item TAINTED_ORE_BORON = new ItemBlock(VRTBlockInit.TAINTED_ORE_BORON);
    public static final Item MOSTLY_TAINTED_ORE_BORON = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_BORON);
    public static final Item PARTIALLY_TAINTED_ORE_BORON = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_BORON);
    public static final Item SLIGHTLY_TAINTED_ORE_BORON = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_BORON);
    public static final Item TAINTED_ORE_COPPER = new ItemBlock(VRTBlockInit.TAINTED_ORE_COPPER);
    public static final Item MOSTLY_TAINTED_ORE_COPPER = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_COPPER);
    public static final Item PARTIALLY_TAINTED_ORE_COPPER = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_COPPER);
    public static final Item SLIGHTLY_TAINTED_ORE_COPPER = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_COPPER);
    public static final Item TAINTED_ORE_GALENA = new ItemBlock(VRTBlockInit.TAINTED_ORE_GALENA);
    public static final Item MOSTLY_TAINTED_ORE_GALENA = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_GALENA);
    public static final Item PARTIALLY_TAINTED_ORE_GALENA = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_GALENA);
    public static final Item SLIGHTLY_TAINTED_ORE_GALENA = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_GALENA);
    public static final Item TAINTED_ORE_GOLD = new ItemBlock(VRTBlockInit.TAINTED_ORE_GOLD);
    public static final Item MOSTLY_TAINTED_ORE_GOLD = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_GOLD);
    public static final Item PARTIALLY_TAINTED_ORE_GOLD = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_GOLD);
    public static final Item SLIGHTLY_TAINTED_ORE_GOLD = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_GOLD);
    public static final Item TAINTED_ORE_IRIDIUM = new ItemBlock(VRTBlockInit.TAINTED_ORE_IRIDIUM);
    public static final Item MOSTLY_TAINTED_ORE_IRIDIUM = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_IRIDIUM);
    public static final Item PARTIALLY_TAINTED_ORE_IRIDIUM = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_IRIDIUM);
    public static final Item SLIGHTLY_TAINTED_ORE_IRIDIUM = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_IRIDIUM);
    public static final Item TAINTED_ORE_IRON = new ItemBlock(VRTBlockInit.TAINTED_ORE_IRON);
    public static final Item MOSTLY_TAINTED_ORE_IRON = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_IRON);
    public static final Item PARTIALLY_TAINTED_ORE_IRON = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_IRON);
    public static final Item SLIGHTLY_TAINTED_ORE_IRON = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_IRON);
    public static final Item TAINTED_ORE_LEAD = new ItemBlock(VRTBlockInit.TAINTED_ORE_LEAD);
    public static final Item MOSTLY_TAINTED_ORE_LEAD = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_LEAD);
    public static final Item PARTIALLY_TAINTED_ORE_LEAD = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_LEAD);
    public static final Item SLIGHTLY_TAINTED_ORE_LEAD = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_LEAD);
    public static final Item TAINTED_ORE_LITHIUM = new ItemBlock(VRTBlockInit.TAINTED_ORE_LITHIUM);
    public static final Item MOSTLY_TAINTED_ORE_LITHIUM = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_LITHIUM);
    public static final Item PARTIALLY_TAINTED_ORE_LITHIUM = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_LITHIUM);
    public static final Item SLIGHTLY_TAINTED_ORE_LITHIUM = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_LITHIUM);
    public static final Item TAINTED_ORE_NICKEL = new ItemBlock(VRTBlockInit.TAINTED_ORE_NICKEL);
    public static final Item MOSTLY_TAINTED_ORE_NICKEL = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_NICKEL);
    public static final Item PARTIALLY_TAINTED_ORE_NICKEL = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_NICKEL);
    public static final Item SLIGHTLY_TAINTED_ORE_NICKEL = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_NICKEL);
    public static final Item TAINTED_ORE_MAGNESIUM = new ItemBlock(VRTBlockInit.TAINTED_ORE_MAGNESIUM);
    public static final Item MOSTLY_TAINTED_ORE_MAGNESIUM = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_MAGNESIUM);
    public static final Item PARTIALLY_TAINTED_ORE_MAGNESIUM = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_MAGNESIUM);
    public static final Item SLIGHTLY_TAINTED_ORE_MAGNESIUM = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_MAGNESIUM);
    public static final Item TAINTED_ORE_SILVER = new ItemBlock(VRTBlockInit.TAINTED_ORE_SILVER);
    public static final Item MOSTLY_TAINTED_ORE_SILVER = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_SILVER);
    public static final Item PARTIALLY_TAINTED_ORE_SILVER = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_SILVER);
    public static final Item SLIGHTLY_TAINTED_ORE_SILVER = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_SILVER);
    public static final Item TAINTED_ORE_THORIUM = new ItemBlock(VRTBlockInit.TAINTED_ORE_THORIUM);
    public static final Item MOSTLY_TAINTED_ORE_THORIUM = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_THORIUM);
    public static final Item PARTIALLY_TAINTED_ORE_THORIUM = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_THORIUM);
    public static final Item SLIGHTLY_TAINTED_ORE_THORIUM = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_THORIUM);
    public static final Item TAINTED_ORE_TIN = new ItemBlock(VRTBlockInit.TAINTED_ORE_TIN);
    public static final Item MOSTLY_TAINTED_ORE_TIN = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_TIN);
    public static final Item PARTIALLY_TAINTED_ORE_TIN = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_TIN);
    public static final Item SLIGHTLY_TAINTED_ORE_TIN = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_TIN);
    public static final Item TAINTED_ORE_URANIUM = new ItemBlock(VRTBlockInit.TAINTED_ORE_URANIUM);
    public static final Item MOSTLY_TAINTED_ORE_URANIUM = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_URANIUM);
    public static final Item PARTIALLY_TAINTED_ORE_URANIUM = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_URANIUM);
    public static final Item SLIGHTLY_TAINTED_ORE_URANIUM = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_URANIUM);
    public static final Item TAINTED_ORE_CERTUS = new ItemBlock(VRTBlockInit.TAINTED_ORE_CERTUS);
    public static final Item MOSTLY_TAINTED_ORE_CERTUS = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_CERTUS);
    public static final Item PARTIALLY_TAINTED_ORE_CERTUS = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_CERTUS);
    public static final Item SLIGHTLY_TAINTED_ORE_CERTUS = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_CERTUS);
    public static final Item TAINTED_ORE_CHARGED_CERTUS = new ItemBlock(VRTBlockInit.TAINTED_ORE_CHARGED_CERTUS);
    public static final Item MOSTLY_TAINTED_ORE_CHARGED_CERTUS = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_CHARGED_CERTUS);
    public static final Item PARTIALLY_TAINTED_ORE_CHARGED_CERTUS = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_CHARGED_CERTUS);
    public static final Item SLIGHTLY_TAINTED_ORE_CHARGED_CERTUS = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_CHARGED_CERTUS);
    public static final Item TAINTED_ORE_COAL = new ItemBlock(VRTBlockInit.TAINTED_ORE_COAL);
    public static final Item MOSTLY_TAINTED_ORE_COAL = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_COAL);
    public static final Item PARTIALLY_TAINTED_ORE_COAL = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_COAL);
    public static final Item SLIGHTLY_TAINTED_ORE_COAL = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_COAL);
    public static final Item TAINTED_ORE_DIAMOND = new ItemBlock(VRTBlockInit.TAINTED_ORE_DIAMOND);
    public static final Item MOSTLY_TAINTED_ORE_DIAMOND = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_DIAMOND);
    public static final Item PARTIALLY_TAINTED_ORE_DIAMOND = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_DIAMOND);
    public static final Item SLIGHTLY_TAINTED_ORE_DIAMOND = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_DIAMOND);
    public static final Item TAINTED_ORE_EMERALD = new ItemBlock(VRTBlockInit.TAINTED_ORE_EMERALD);
    public static final Item MOSTLY_TAINTED_ORE_EMERALD = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_EMERALD);
    public static final Item PARTIALLY_TAINTED_ORE_EMERALD = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_EMERALD);
    public static final Item SLIGHTLY_TAINTED_ORE_EMERALD = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_EMERALD);
    public static final Item TAINTED_ORE_LAPIS = new ItemBlock(VRTBlockInit.TAINTED_ORE_LAPIS);
    public static final Item MOSTLY_TAINTED_ORE_LAPIS = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_LAPIS);
    public static final Item PARTIALLY_TAINTED_ORE_LAPIS = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_LAPIS);
    public static final Item SLIGHTLY_TAINTED_ORE_LAPIS = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_LAPIS);
    public static final Item TAINTED_ORE_REDSTONE = new ItemBlock(VRTBlockInit.TAINTED_ORE_REDSTONE);
    public static final Item MOSTLY_TAINTED_ORE_REDSTONE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_REDSTONE);
    public static final Item PARTIALLY_TAINTED_ORE_REDSTONE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_REDSTONE);
    public static final Item SLIGHTLY_TAINTED_ORE_REDSTONE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_REDSTONE);
    public static final Item TAINTED_ORE_RUBY = new ItemBlock(VRTBlockInit.TAINTED_ORE_RUBY);
    public static final Item MOSTLY_TAINTED_ORE_RUBY = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_RUBY);
    public static final Item PARTIALLY_TAINTED_ORE_RUBY = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_RUBY);
    public static final Item SLIGHTLY_TAINTED_ORE_RUBY = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_RUBY);
    public static final Item TAINTED_ORE_SAPPHIRE = new ItemBlock(VRTBlockInit.TAINTED_ORE_SAPPHIRE);
    public static final Item MOSTLY_TAINTED_ORE_SAPPHIRE = new ItemBlock(VRTBlockInit.MOSTLY_TAINTED_ORE_SAPPHIRE);
    public static final Item PARTIALLY_TAINTED_ORE_SAPPHIRE = new ItemBlock(VRTBlockInit.PARTIALLY_TAINTED_ORE_SAPPHIRE);
    public static final Item SLIGHTLY_TAINTED_ORE_SAPPHIRE = new ItemBlock(VRTBlockInit.SLIGHTLY_TAINTED_ORE_SAPPHIRE);
    //
    // Items
    //
    public static final Item CHARRED_TAINT = new VRTItemBase("charred_taint");
    public static final Item BOSS_SUMMON_ITEM = new BossSummonItem("boss_summon");

    public static final Hashtable<String, List<Item>> TAINTED_ITEMS = new Hashtable<String, List<Item>>() {{
        put("tainted_andesite", Arrays.asList(SLIGHTLY_TAINTED_ANDESITE, PARTIALLY_TAINTED_ANDESITE, MOSTLY_TAINTED_ANDESITE, TAINTED_ANDESITE));
        put("tainted_clay", Arrays.asList(SLIGHTLY_TAINTED_CLAY, PARTIALLY_TAINTED_CLAY, MOSTLY_TAINTED_CLAY, TAINTED_CLAY));
        put("tainted_cobblestone", Arrays.asList(SLIGHTLY_TAINTED_COBBLESTONE, PARTIALLY_TAINTED_COBBLESTONE, MOSTLY_TAINTED_COBBLESTONE, TAINTED_COBBLESTONE));
        put("tainted_diorite", Arrays.asList(SLIGHTLY_TAINTED_DIORITE, PARTIALLY_TAINTED_DIORITE, MOSTLY_TAINTED_DIORITE, TAINTED_DIORITE));
        put("tainted_dirt", Arrays.asList(SLIGHTLY_TAINTED_DIRT, PARTIALLY_TAINTED_DIRT, MOSTLY_TAINTED_DIRT, TAINTED_DIRT));
        put("tainted_stone", Arrays.asList(SLIGHTLY_TAINTED_STONE, PARTIALLY_TAINTED_STONE, MOSTLY_TAINTED_STONE, TAINTED_STONE));
        put("tainted_granite", Arrays.asList(SLIGHTLY_TAINTED_GRANITE, PARTIALLY_TAINTED_GRANITE, MOSTLY_TAINTED_GRANITE, TAINTED_GRANITE));
        put("tainted_gravel", Arrays.asList(SLIGHTLY_TAINTED_GRAVEL, PARTIALLY_TAINTED_GRAVEL, MOSTLY_TAINTED_GRAVEL, TAINTED_GRAVEL));
        put("tainted_sand", Arrays.asList(SLIGHTLY_TAINTED_SAND, PARTIALLY_TAINTED_SAND, MOSTLY_TAINTED_SAND, TAINTED_SAND));
        put("tainted_sandstone", Arrays.asList(SLIGHTLY_TAINTED_SANDSTONE, PARTIALLY_TAINTED_SANDSTONE, MOSTLY_TAINTED_SANDSTONE, TAINTED_SANDSTONE));
        put("tainted_stone_bricks", Arrays.asList(SLIGHTLY_TAINTED_STONE_BRICKS, PARTIALLY_TAINTED_STONE_BRICKS, MOSTLY_TAINTED_STONE_BRICKS, TAINTED_STONE_BRICKS));
        put("tainted_ore_bauxite", Arrays.asList(SLIGHTLY_TAINTED_ORE_BAUXITE, PARTIALLY_TAINTED_ORE_BAUXITE, MOSTLY_TAINTED_ORE_BAUXITE, TAINTED_ORE_BAUXITE));
        put("tainted_ore_boron", Arrays.asList(SLIGHTLY_TAINTED_ORE_BORON, PARTIALLY_TAINTED_ORE_BORON, MOSTLY_TAINTED_ORE_BORON, TAINTED_ORE_BORON));
        put("tainted_ore_copper", Arrays.asList(SLIGHTLY_TAINTED_ORE_COPPER, PARTIALLY_TAINTED_ORE_COPPER, MOSTLY_TAINTED_ORE_COPPER, TAINTED_ORE_COPPER));
        put("tainted_ore_galena", Arrays.asList(SLIGHTLY_TAINTED_ORE_GALENA, PARTIALLY_TAINTED_ORE_GALENA, MOSTLY_TAINTED_ORE_GALENA, TAINTED_ORE_GALENA));
        put("tainted_ore_gold", Arrays.asList(SLIGHTLY_TAINTED_ORE_GOLD, PARTIALLY_TAINTED_ORE_GOLD, MOSTLY_TAINTED_ORE_GOLD, TAINTED_ORE_GOLD));
        put("tainted_ore_iridium", Arrays.asList(SLIGHTLY_TAINTED_ORE_IRIDIUM, PARTIALLY_TAINTED_ORE_IRIDIUM, MOSTLY_TAINTED_ORE_IRIDIUM, TAINTED_ORE_IRIDIUM));
        put("tainted_ore_iron", Arrays.asList(SLIGHTLY_TAINTED_ORE_IRON, PARTIALLY_TAINTED_ORE_IRON, MOSTLY_TAINTED_ORE_IRON, TAINTED_ORE_IRON));
        put("tainted_ore_lead", Arrays.asList(SLIGHTLY_TAINTED_ORE_LEAD, PARTIALLY_TAINTED_ORE_LEAD, MOSTLY_TAINTED_ORE_LEAD, TAINTED_ORE_LEAD));
        put("tainted_ore_lithium", Arrays.asList(SLIGHTLY_TAINTED_ORE_LITHIUM, PARTIALLY_TAINTED_ORE_LITHIUM, MOSTLY_TAINTED_ORE_LITHIUM, TAINTED_ORE_LITHIUM));
        put("tainted_ore_nickel", Arrays.asList(SLIGHTLY_TAINTED_ORE_NICKEL, PARTIALLY_TAINTED_ORE_NICKEL, MOSTLY_TAINTED_ORE_NICKEL, TAINTED_ORE_NICKEL));
        put("tainted_ore_magnesium", Arrays.asList(SLIGHTLY_TAINTED_ORE_MAGNESIUM, PARTIALLY_TAINTED_ORE_MAGNESIUM, MOSTLY_TAINTED_ORE_MAGNESIUM, TAINTED_ORE_MAGNESIUM));
        put("tainted_ore_silver", Arrays.asList(SLIGHTLY_TAINTED_ORE_SILVER, PARTIALLY_TAINTED_ORE_SILVER, MOSTLY_TAINTED_ORE_SILVER, TAINTED_ORE_SILVER));
        put("tainted_ore_thorium", Arrays.asList(SLIGHTLY_TAINTED_ORE_THORIUM, PARTIALLY_TAINTED_ORE_THORIUM, MOSTLY_TAINTED_ORE_THORIUM, TAINTED_ORE_THORIUM));
        put("tainted_ore_tin", Arrays.asList(SLIGHTLY_TAINTED_ORE_TIN, PARTIALLY_TAINTED_ORE_TIN, MOSTLY_TAINTED_ORE_TIN, TAINTED_ORE_TIN));
        put("tainted_ore_uranium", Arrays.asList(SLIGHTLY_TAINTED_ORE_URANIUM, PARTIALLY_TAINTED_ORE_URANIUM, MOSTLY_TAINTED_ORE_URANIUM, TAINTED_ORE_URANIUM));
        put("tainted_ore_certus", Arrays.asList(SLIGHTLY_TAINTED_ORE_CERTUS, PARTIALLY_TAINTED_ORE_CERTUS, MOSTLY_TAINTED_ORE_CERTUS, TAINTED_ORE_CERTUS));
        put("tainted_ore_charged_certus", Arrays.asList(SLIGHTLY_TAINTED_ORE_CHARGED_CERTUS, PARTIALLY_TAINTED_ORE_CHARGED_CERTUS, MOSTLY_TAINTED_ORE_CHARGED_CERTUS, TAINTED_ORE_CHARGED_CERTUS));
        put("tainted_ore_coal", Arrays.asList(SLIGHTLY_TAINTED_ORE_COAL, PARTIALLY_TAINTED_ORE_COAL, MOSTLY_TAINTED_ORE_COAL, TAINTED_ORE_COAL));
        put("tainted_ore_diamond", Arrays.asList(SLIGHTLY_TAINTED_ORE_DIAMOND, PARTIALLY_TAINTED_ORE_DIAMOND, MOSTLY_TAINTED_ORE_DIAMOND, TAINTED_ORE_DIAMOND));
        put("tainted_ore_emerald", Arrays.asList(SLIGHTLY_TAINTED_ORE_EMERALD, PARTIALLY_TAINTED_ORE_EMERALD, MOSTLY_TAINTED_ORE_EMERALD, TAINTED_ORE_EMERALD));
        put("tainted_ore_lapis", Arrays.asList(SLIGHTLY_TAINTED_ORE_LAPIS, PARTIALLY_TAINTED_ORE_LAPIS, MOSTLY_TAINTED_ORE_LAPIS, TAINTED_ORE_LAPIS));
        put("tainted_ore_redstone", Arrays.asList(SLIGHTLY_TAINTED_ORE_REDSTONE, PARTIALLY_TAINTED_ORE_REDSTONE, MOSTLY_TAINTED_ORE_REDSTONE, TAINTED_ORE_REDSTONE));
        put("tainted_ore_ruby", Arrays.asList(SLIGHTLY_TAINTED_ORE_RUBY, PARTIALLY_TAINTED_ORE_RUBY, MOSTLY_TAINTED_ORE_RUBY, TAINTED_ORE_RUBY));
        put("tainted_ore_sapphire", Arrays.asList(SLIGHTLY_TAINTED_ORE_SAPPHIRE, PARTIALLY_TAINTED_ORE_SAPPHIRE, MOSTLY_TAINTED_ORE_SAPPHIRE, TAINTED_ORE_SAPPHIRE));
    }};
}
